'use client';

import Link from 'next/link';
import { useEffect, useState, type ReactNode } from 'react';
import { ArrowRight, Headphones, LayoutDashboard, LogOut, Menu, Settings, Sparkles, UserRound, X } from 'lucide-react';
import { getCurrentUser, getProfile, signOut } from '@/lib/supabase-auth';

export default function ProtectedShell({ children, admin = false }: { children: ReactNode; admin?: boolean }) {
  const [checking, setChecking] = useState(true); const [user, setUser] = useState<any>(null); const [profile, setProfile] = useState<any>(null); const [mobile, setMobile] = useState(false);
  useEffect(() => { (async () => { const current = await getCurrentUser(); if (!current) { window.location.href = admin ? '/admin/login' : '/login'; return; } const p = await getProfile(current.id); if (admin && p?.role !== 'admin') { window.location.href = '/dashboard'; return; } setUser(current); setProfile(p); setChecking(false); })(); }, [admin]);
  if (checking) return <div className="flex min-h-screen items-center justify-center bg-gray-50"><div className="rounded-2xl border border-gray-200 bg-white px-6 py-5 text-sm text-gray-500 shadow-sm">Checking account…</div></div>;
  const links = admin ? [{ href: '/admin', label: 'Dashboard', icon: LayoutDashboard }, { href: '/admin?tab=users', label: 'Users', icon: UserRound }, { href: '/admin?tab=orders', label: 'Orders', icon: ArrowRight }, { href: '/admin?tab=payments', label: 'Payments', icon: Sparkles }, { href: '/admin?tab=pricing', label: 'Pricing', icon: Settings }] : [{ href: '/dashboard', label: 'Overview', icon: LayoutDashboard }, { href: '/#generator', label: 'Generate TTS', icon: Sparkles }, { href: '/dashboard?tab=orders', label: 'My Orders', icon: ArrowRight }, { href: '/dashboard?tab=audio', label: 'My Audio', icon: Headphones }, { href: '/dashboard?tab=profile', label: 'Profile', icon: UserRound }];
  return <div className="min-h-screen bg-gray-50 text-gray-950"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 border-r border-gray-200 bg-white lg:flex lg:flex-col"><div className="flex h-16 items-center border-b border-gray-100 px-6"><Link href="/" className="text-xl font-bold">Prose<span className="text-purple-600">Text</span></Link></div><nav className="flex-1 space-y-1 p-4">{links.map(({ href, label, icon: Icon }) => <Link key={label} href={href} className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-gray-600 hover:bg-purple-50 hover:text-purple-700"><Icon size={18}/>{label}</Link>)}</nav><div className="border-t border-gray-100 p-4"><div className="mb-3 rounded-xl bg-gray-50 p-3"><p className="truncate text-sm font-semibold">{profile?.full_name || user?.email}</p><p className="truncate text-xs text-gray-500">{admin ? 'Administrator' : user?.email}</p></div><button onClick={() => { signOut(); window.location.href = '/'; }} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-gray-600 hover:bg-red-50 hover:text-red-600"><LogOut size={18}/>Sign out</button></div></aside><div className="lg:pl-64"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-gray-200 bg-white/90 px-4 backdrop-blur-xl sm:px-6"><button className="rounded-xl p-2 lg:hidden" onClick={() => setMobile(true)}><Menu size={22}/></button><div className="ml-auto flex items-center gap-3"><span className="hidden text-sm text-gray-500 sm:block">{admin ? 'Admin Console' : 'ProseText Workspace'}</span><div className="flex h-9 w-9 items-center justify-center rounded-full bg-purple-100 text-sm font-bold text-purple-700">{(profile?.full_name || user?.email || 'V').charAt(0).toUpperCase()}</div></div></header><main className="p-4 sm:p-6 lg:p-8">{children}</main></div>{mobile ? <div className="fixed inset-0 z-50 bg-gray-950/40 lg:hidden" onClick={() => setMobile(false)}><aside className="h-full w-72 bg-white p-5" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between"><Link href="/" className="text-xl font-bold">Prose<span className="text-purple-600">Text</span></Link><button onClick={() => setMobile(false)} className="rounded-xl p-2"><X size={20}/></button></div><nav className="mt-8 space-y-1">{links.map(({ href, label, icon: Icon }) => <Link onClick={() => setMobile(false)} key={label} href={href} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium text-gray-600 hover:bg-purple-50 hover:text-purple-700"><Icon size={18}/>{label}</Link>)}</nav></aside></div> : null}</div>;
}
